name: expense
networks:
  default:
    external: true
    name: expense
services:
  mysql: 
    image: mysql:1.0.0
    container_name: mysql # -- name mysql
  backend:
    image: backend:1.0.0
    container_name: backend # -- name backend
    depends_on:
      - mysql
  frontend:
    image: frontend:1.0.0
    container_name: frontend # -- name frontend
    depends_on:
      - backend
    ports:
      - "80:80"