name: expense
version: "3.8"
networks:
  default:
    external: true
    name: expense
volumes:
  mysql:
services:
  mysql: 
    image: ./mysql
    container_name: mysql # -- name mysql
    volumes:
      - mysql:/var/lib/mysql # -v <volume-name>:/path/in/container
  backend:
    image: ./backend
    container_name: backend # -- name backend
    command: sh -c "sleep 20  && node /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: ./frontend
    container_name: frontend # -- name frontend
    depends_on:
      - backend
    ports:
      - "80:80"